python3 opencv-custom.py --input imgs/grzyby.png --output output/grzyby-usredniaj-cv.png --kernel matrices/usredniaj.txt
python3 opencv-custom.py --input imgs/grzyby.png --output output/grzyby-gauss-cv.png --kernel matrices/gauss.txt
python3 opencv-custom.py --input imgs/grzyby.png --output output/grzyby-sobel-cv.png --kernel matrices/sobel.txt
python3 opencv-custom.py --input imgs/grzyby.png --output output/grzyby-mean_removal-cv.png --kernel matrices/mean_removal.txt
python3 opencv-custom.py --input imgs/grzyby.png --output output/grzyby-laplace-cv.png --kernel matrices/laplace.txt
python3 opencv-custom.py --input imgs/hotel.png --output output/hotel-usredniaj-cv.png --kernel matrices/usredniaj.txt
python3 opencv-custom.py --input imgs/hotel.png --output output/hotel-gauss-cv.png --kernel matrices/gauss.txt
python3 opencv-custom.py --input imgs/hotel.png --output output/hotel-sobel-cv.png --kernel matrices/sobel.txt
python3 opencv-custom.py --input imgs/hotel.png --output output/hotel-mean_removal-cv.png --kernel matrices/mean_removal.txt
python3 opencv-custom.py --input imgs/hotel.png --output output/hotel-laplace-cv.png --kernel matrices/laplace.txt
